language: python

# Please don't spam me with email
notifications:
  email: false

python:
  - "2.7"
# Install dependencies
install: "pip install behave mechanize beautifulsoup"
# Command to run the tests
script: behave -k --tags wip