language: python

# Please don't spam me with email
notifications:
    email: false

python:
    - 2.7

# Install dependencies
install: "pip install -r requirements.txt"
# Command to run the tests

# k - Don't print skipped tests, c - No color output, --no-capture - Don't capture std-out
script: behave -ck --no-capture --tags @travis
