language: python

# Please don't spam me with email
notifications:
    email: false

python:
    - 2.7
    - 3.2

matrix:
    allow_failures:
        - python: 3.2

# Install dependencies
install: "pip install behave mechanize beautifulsoup"
# Command to run the tests
script: behave -k --tags wip